# Meta Ad Library Scraper

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mamoo85/open-data-actor-notebooks/blob/main/notebooks/meta-ad-library.ipynb)

**What:** Image or video URL on 100% of ads vs 70% in our side-by-side test, at $0.00065 per ad. Search the public Meta Ad Library by keyword, advertiser Page id or library URL. No login. Flat rows: ad text, headline, link, CTA, media URLs, ISO dates, platforms, variations.

**Why:** run the [`meta-ad-library`](https://apify.com/transparent_meteorite/meta-ad-library) Apify actor from Python and analyse the result as a pandas DataFrame, with no scraping code to maintain.

> **Disclosure:** I am the author of this actor. It is pay-per-result; the free plan credit on a new Apify account covers a trial run like this one (this notebook uses a very small sample input).

## 1. Setup

In [1]:
!pip install -q apify-client pandas

import os, getpass
try:
    from google.colab import userdata
    APIFY_TOKEN = userdata.get('APIFY_TOKEN')          # Colab: add it under the key icon (Secrets)
except Exception:
    APIFY_TOKEN = os.environ.get('APIFY_TOKEN') or getpass.getpass('Apify API token: ')
assert APIFY_TOKEN, 'An Apify API token is required (a free account is enough).'
print('Token loaded.')

Token loaded.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## 2. Input
A deliberately small sample so the run is cheap and quick. See the [actor page](https://apify.com/transparent_meteorite/meta-ad-library) for every option.

In [2]:
run_input = {'searchTerms': ['running shoes'], 'country': 'US', 'maxItems': 3}

## 3. Run the actor and read the dataset

In [3]:
from apify_client import ApifyClient

client = ApifyClient(APIFY_TOKEN)
run = client.actor('transparent_meteorite/meta-ad-library').call(run_input=run_input)
# apify-client v2 returns a dict, v3 a Run object; handle both
get = (lambda k, a: run[k]) if isinstance(run, dict) else (lambda k, a: getattr(run, a))
items = list(client.dataset(get('defaultDatasetId', 'default_dataset_id')).iterate_items())
print('Run status:', get('status', 'status'), '| items:', len(items))

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> Status: RUNNING, Message:

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:49.795Z ACTOR: Pulling container image of build ZoKT1HjhSI6n1Z8AM from registry.

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:50.445Z ACTOR: Creating container.

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:50.513Z ACTOR: Starting container.

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:50.517Z ACTOR: Running under "LIMITED_PERMISSIONS".

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:50.976Z INFO  System info {"apifyVersion":"3.7.2","apifyClientVersion":"2.23.3","crawleeVersion":"3.16.0","osType":"Linux","nodeVersion":"v20.20.2"}

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:50.981Z INFO  [Status message]: Starting Meta Ad Library: reading input

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> Status: RUNNING, Message: Starting Meta Ad Library: reading input

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> Status: RUNNING, Message: Searching the Meta Ad Library for 1 target(s)

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:51.150Z INFO  [Status message]: Searching the Meta Ad Library for 1 target(s)

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:54.414Z INFO  [Status message]: Meta Ad Library: 1 items so far

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:54.687Z INFO  [Status message]: running shoes: 3 ads of ~41847

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:54.721Z Done. Delivered 3 ads (charged 3).

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:54.791Z INFO  [Status message]: Done: 3 items

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> 2026-10-13T22:25:54.864Z Thanks for using Meta Ad Library. Found a bug or need a field? Open an issue on the Issues tab (https://console.apify.com/actors/bLbk5BQwyr2vDpHdv/issues) with the run URL and we will reply there.

[apify.meta-ad-library runId:qjAfeUOVwFPPjCf4n] -> Status: SUCCEEDED, Message: Done: 3 items

Run status: SUCCEEDED | items: 3

## 4. Tabulate

In [4]:
import pandas as pd
pd.set_option('display.max_colwidth', 70)
pd.set_option('display.width', 200)

df = pd.DataFrame(items)

# Privacy: remove contact / personal-data columns before anything is displayed
DROP = ["email", "phone", "author", "registeredagent", "contractor", "officer", "linkedin", "facebook", "instagram", "youtube", "tiktok", "socials", "twitter"]
KEEP = ["emailCount", "phoneCount", "emailProvider"]
df = df[[c for c in df.columns if c in KEEP or not any(p in c.lower() for p in DROP)]]
SHOW = [c for c in ["pageName", "isActive", "startDate", "daysRunning", "platforms", "ctaText", "displayFormat", "mediaType", "variationsCount"] if c in df.columns]
df[SHOW]

                       pageName  isActive   startDate  daysRunning                                                    platforms     ctaText displayFormat mediaType  variationsCount
0  Cholesterol Relief Community      True  2026-06-01          134   [FACEBOOK, INSTAGRAM, AUDIENCE_NETWORK, WHATSAPP, THREADS]  Learn more         IMAGE     image                1
1  Cholesterol Relief Community      True  2026-05-26          140   [FACEBOOK, INSTAGRAM, AUDIENCE_NETWORK, WHATSAPP, THREADS]  Learn more         IMAGE     image                1
2                       Saucony      True  2026-02-22          233  [FACEBOOK, INSTAGRAM, AUDIENCE_NETWORK, MESSENGER, THREADS]    Shop now           DPA     image                1

## 5. A quick analysis

In [5]:
df['daysRunning']=pd.to_numeric(df['daysRunning'],errors='coerce')
print(df['displayFormat'].value_counts(dropna=False))
df.sort_values('daysRunning',ascending=False)[['pageName','daysRunning','ctaText']].head(5)

displayFormat
IMAGE    2
DPA      1
Name: count, dtype: int64

                       pageName  daysRunning     ctaText
2                       Saucony          233    Shop now
1  Cholesterol Relief Community          140  Learn more
0  Cholesterol Relief Community          134  Learn more

## Next steps

- Raise the limits in the input cell to run a larger sample.
- Schedule the actor or call it from your own pipeline: [meta-ad-library on the Apify Store](https://apify.com/transparent_meteorite/meta-ad-library).
- Check the Store page for the current pay-per-result price before scaling up.

Generated by `tools/generate.py`.