# SAM.gov Contract Opportunities

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mamoo85/open-data-actor-notebooks/blob/main/notebooks/sam-gov-opportunities.ipynb)

**What:** Get open federal contracts and government bids from SAM.gov: solicitations, RFPs, RFQs, sources sought and award notices with contracting officer email and phone, NAICS, PSC, set-aside, deadlines, full text and attachments. No API key needed; daily new-only monitor mode.

**Why:** run the [`sam-gov-opportunities`](https://apify.com/transparent_meteorite/sam-gov-opportunities) Apify actor from Python and analyse the result as a pandas DataFrame, with no scraping code to maintain.

> **Disclosure:** I am the author of this actor. It is pay-per-result; the free plan credit on a new Apify account covers a trial run like this one (this notebook uses a very small sample input).

**Privacy:** Contracting-officer names, emails and phone numbers are not displayed; notice-level fields only.

## 1. Setup

In [1]:
!pip install -q apify-client pandas

import os, getpass
try:
    from google.colab import userdata
    APIFY_TOKEN = userdata.get('APIFY_TOKEN')          # Colab: add it under the key icon (Secrets)
except Exception:
    APIFY_TOKEN = os.environ.get('APIFY_TOKEN') or getpass.getpass('Apify API token: ')
assert APIFY_TOKEN, 'An Apify API token is required (a free account is enough).'
print('Token loaded.')

Token loaded.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## 2. Input
A deliberately small sample so the run is cheap and quick. See the [actor page](https://apify.com/transparent_meteorite/sam-gov-opportunities) for every option.

In [2]:
run_input = {'keywords': ['software'], 'postedWithinDays': 7, 'maxResults': 3}

## 3. Run the actor and read the dataset

In [3]:
from apify_client import ApifyClient

client = ApifyClient(APIFY_TOKEN)
run = client.actor('transparent_meteorite/sam-gov-opportunities').call(run_input=run_input)
# apify-client v2 returns a dict, v3 a Run object; handle both
get = (lambda k, a: run[k]) if isinstance(run, dict) else (lambda k, a: getattr(run, a))
items = list(client.dataset(get('defaultDatasetId', 'default_dataset_id')).iterate_items())
print('Run status:', get('status', 'status'), '| items:', len(items))

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> Status: RUNNING, Message:

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> 2026-10-14T07:15:45.668Z ACTOR: Pulling container image of build DMXtTcc2sDvCT4910 from registry.

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> 2026-10-14T07:15:46.308Z ACTOR: Creating container.

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> 2026-10-14T07:15:46.379Z ACTOR: Starting container.

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> 2026-10-14T07:15:46.380Z ACTOR: Running under "LIMITED_PERMISSIONS".

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> 2026-10-14T07:15:46.962Z INFO  System info {"apifyVersion":"3.7.2","apifyClientVersion":"2.23.3","crawleeVersion":"3.16.0","osType":"Linux","nodeVersion":"v20.20.2"}

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> Status: RUNNING, Message: Starting SAM.gov Contract Opportunities: reading input

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> 2026-10-14T07:15:46.968Z INFO  [Status message]: Starting SAM.gov Contract Opportunities: reading input

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> Status: RUNNING, Message: "software": 256 match; page 1, 0 delivered

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> 2026-10-14T07:15:47.257Z INFO  [Status message]: "software": 256 match; page 1, 0 delivered

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> 2026-10-14T07:15:48.447Z INFO  [Status message]: SAM.gov Contract Opportunities: 1 items so far

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> 2026-10-14T07:15:49.120Z Done. Delivered 3 opportunities (charged 3); 0 skipped as already seen; 4 requests.

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> Status: RUNNING, Message: Done: 3 items

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> 2026-10-14T07:15:49.123Z INFO  [Status message]: Done: 3 items

[apify.sam-gov-opportunities runId:Gr5LA1M5oiOuZSFfH] -> 2026-10-14T07:15:49.175Z Thanks for using SAM.gov Contract Opportunities. Found a bug or need a field? Open an issue on the Issues tab (https://console.apify.com/actors/xbs7khrbMqLAHREjm/issues) with the run URL and we will reply there.

Run status: SUCCEEDED | items: 3

## 4. Tabulate

Contracting-officer names, emails and phone numbers are not displayed; notice-level fields only.

In [4]:
import pandas as pd
pd.set_option('display.max_colwidth', 70)
pd.set_option('display.width', 200)

df = pd.DataFrame(items)

# Privacy: remove contact / personal-data columns before anything is displayed
DROP = ["email", "phone", "author", "registeredagent", "contractor", "officer", "linkedin", "facebook", "instagram", "youtube", "tiktok", "socials", "twitter"]
KEEP = ["emailCount", "phoneCount", "emailProvider"]
df = df[[c for c in df.columns if c in KEEP or not any(p in c.lower() for p in DROP)]]
SHOW = [c for c in ["title", "solicitationNumber", "noticeType", "postedDate", "responseDeadline", "department", "naicsCode", "pscCode", "setAside", "samUrl"] if c in df.columns]
df[SHOW]

,title,solicitationNumber,noticeType,postedDate,responseDeadline,department,naicsCode,pscCode,setAside,samUrl
0,JetBrains Renewal,N6893627Q0006,Combined Synopsis/Solicitation,2026-10-13T22:42:51.226+00:00,2026-10-22T16:00:00-07:00,DEPT OF DEFENSE,513210,7A21,NaN,https://sam.gov/opp/f3307225f3b54ae5a14f43186836f22f/view
1,"Admin Management, Data Management, Software Development (Quality A...",36C26026Q1017,Combined Synopsis/Solicitation,2026-10-13T22:26:14.596+00:00,2026-11-03T17:00:00-08:00,"VETERANS AFFAIRS, DEPARTMENT OF",541519,H979,SDVOSBC,https://sam.gov/opp/f50d635e4b9d4404916c47df2357fc66/view
2,AdaCore GNAT Pro Enterprise Software Support,N6893627Q0004,Combined Synopsis/Solicitation,2026-10-13T22:24:26.248+00:00,2026-10-22T10:00:00-07:00,DEPT OF DEFENSE,513210,7A21,NaN,https://sam.gov/opp/fc1cd1d996134a239e806a0309229a6c/view

## 5. A quick analysis

In [5]:
print(df['noticeType'].value_counts())
print(df['department'].value_counts().head(8))
df.sort_values('responseDeadline')[['title','department','responseDeadline']].head(10)

noticeType
Combined Synopsis/Solicitation    3
Name: count, dtype: int64
department
DEPT OF DEFENSE                    2
VETERANS AFFAIRS, DEPARTMENT OF    1
Name: count, dtype: int64

                                                                   title                       department           responseDeadline
2                           AdaCore GNAT Pro Enterprise Software Support                  DEPT OF DEFENSE  2026-10-22T10:00:00-07:00
0                                                      JetBrains Renewal                  DEPT OF DEFENSE  2026-10-22T16:00:00-07:00
1  Admin Management, Data Management, Software Development (Quality A...  VETERANS AFFAIRS, DEPARTMENT OF  2026-11-03T17:00:00-08:00

## Next steps

- Raise the limits in the input cell to run a larger sample.
- Schedule the actor or call it from your own pipeline: [sam-gov-opportunities on the Apify Store](https://apify.com/transparent_meteorite/sam-gov-opportunities).
- Check the Store page for the current pay-per-result price before scaling up.

Generated by `tools/generate.py`.